name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: make
      run: bazel build //lib:test_cmd_list  --test_output=all  -c dbg
    - name: unit test
      run: ./bazel-bin/lib/test_cmd_list
